/** Backend público de pré-solicitações. Configuração operacional: Script Properties. */
var SERVICE_NAME = 'pati-mundopet-scheduling';
var SERVICE_VERSION = '2.5.0';
var MAX_FUTURE_DAYS = 90;
var LOCK_TIMEOUT_MS = 5000;
var REQUIRED_PROPERTIES = ['AVAILABILITY_CALENDAR_ID','APPOINTMENTS_CALENDAR_ID','SPREADSHEET_ID','TIMEZONE','WORKDAY_START_TIME','WORKDAY_END_TIME','SLOT_INTERVAL_MINUTES','ALLOWED_SERVICE_IDS_JSON','WHATSAPP_NUMBER','PRIVACY_POLICY_VERSION','MAX_REQUEST_BYTES','RATE_LIMIT_WINDOW_MINUTES','RATE_LIMIT_MAX_REQUESTS','RATE_LIMIT_SALT','NOTIFICATION_EMAIL','EMAIL_NOTIFICATIONS_ENABLED'];
var ALLOWED_POST_FIELDS = ['action','serviceId','date','time','startTime','endTime','responsibleName','whatsapp','petName','region','address','notes','reviewAccepted','privacyAccepted','privacyPolicyVersion','honeypot','requestId','email','submissionChannel'];
var TEXT_LIMITS = {serviceId:80,responsibleName:120,whatsapp:20,email:254,submissionChannel:10,petName:80,region:120,address:250,notes:1000,privacyPolicyVersion:80,requestId:36};
var SHEET_HEADERS = {
  requests:['requestId','dataRecebimento','submissionChannel','serviço','data','horário','responsável','WhatsApp','e-mail','pet','região','observações','status','notificationStatus','dataÚltimaAtualização'],
  requestEnd:'horárioTérmino', requestEvent:'eventIdAtendimento', requestAdminNote:'observaçãoAdministrativa', requestClientId:'clienteId', requestAddress:'endereço',
  clients:['clienteId','responsável','WhatsApp','e-mail','pets','observações','dataCadastro','últimoAtendimento'],
  payments:['requestId','cliente','serviço','valor','formaPagamento','vencimento','statusPagamento','dataPagamento','observações']
};

function doGet(e){try{var action=getParameter_(e,'action');if(action==='health')return jsonResponse_(healthResponse_());if(action==='availability')return jsonResponse_(availabilityResponse_(getParameter_(e,'date'),getParameter_(e,'startTime'),getParameter_(e,'endTime')));if(action==='request-status')return jsonResponse_(requestStatusResponse_(getParameter_(e,'requestId')));return jsonResponse_(invalidRequest_());}catch(error){logTechnical_('GET_INTERNAL');return jsonResponse_(response_(false,'INTERNAL_ERROR','Não foi possível processar a solicitação.'));}}
function doPost(e){var requestId='';try{var loaded=loadConfig_();if(!loaded.ok)return jsonResponse_(configurationRequired_());var parsed=parsePostPayload_(e,loaded.config.maxRequestBytes);if(!parsed.ok||parsed.payload.action!=='request')return jsonResponse_(invalidRequest_());requestId=String(parsed.payload.requestId||'');return jsonResponse_(requestResponse_(parsed.payload,loaded.config));}catch(error){logTechnical_('POST_INTERNAL',requestId);return jsonResponse_(response_(false,'INTERNAL_ERROR','Não foi possível processar a solicitação.',requestId));}}
function invalidRequest_(){return response_(false,'INVALID_REQUEST','Solicitação inválida.');}
function healthResponse_(){var p=PropertiesService.getScriptProperties().getProperties(),loaded=loadConfig_(),spreadsheetLoaded=loadSpreadsheetConfig_(p),calendars={ok:false},requests={ok:false};if(loaded.ok)calendars=getCalendars_(loaded.config);if(spreadsheetLoaded.ok)requests=getValidatedRequestSheet_(spreadsheetLoaded.config);var availabilityReady=loaded.ok&&calendars.ok,requestSheetReady=spreadsheetLoaded.ok&&requests.ok,requestEndTimeReady=requestSheetReady&&requests.requests.hasEndTime;return {ok:true,code:'HEALTH_OK',message:'Serviço de diagnóstico disponível.',service:SERVICE_NAME,version:SERVICE_VERSION,configured:loaded.ok,spreadsheetConfigured:hasProperty_(p,'SPREADSHEET_ID'),availabilityCalendarConfigured:hasProperty_(p,'AVAILABILITY_CALENDAR_ID'),appointmentsCalendarConfigured:hasProperty_(p,'APPOINTMENTS_CALENDAR_ID'),availabilityReady:availabilityReady,requestReady:availabilityReady&&requestEndTimeReady,requestSheetReady:requestSheetReady,requestEndTimeReady:requestEndTimeReady,timestamp:new Date().toISOString()};}

function requestStatusResponse_(requestId){if(!requestId||!validRequestId_(requestId))return invalidRequest_();var loaded=loadSpreadsheetConfig_();if(!loaded.ok)return requestStatusUnavailable_();var sheets=getValidatedRequestSheet_(loaded.config);if(!sheets.ok)return requestStatusUnavailable_();var matches=findRequestRows_(sheets.requests,requestId.trim());if(matches.length===0)return response_(false,'REQUEST_NOT_FOUND','Pré-solicitação não encontrada.',requestId.trim());if(matches.length>1)return response_(false,'INCONSISTENT_STATE','Não foi possível consultar a pré-solicitação.',requestId.trim());return response_(true,'REQUEST_FOUND','Pré-solicitação encontrada.',requestId.trim(),{requestId:requestId.trim(),status:String(matches[0].values[12]||'')});}
function configurationRequired_(requestId){return response_(false,'CONFIGURATION_REQUIRED','Não foi possível registrar a pré-solicitação porque o sistema administrativo está temporariamente indisponível. Nenhuma solicitação foi registrada.',requestId);}
function requestStatusUnavailable_(){return response_(false,'CONFIGURATION_REQUIRED','Não foi possível confirmar agora se a pré-solicitação foi registrada. Tente novamente em instantes.');}

function availabilityResponse_(dateText,startTime,endTime){
  var loaded=loadConfig_();if(!loaded.ok)return response_(false,'CONFIGURATION_REQUIRED','A integração ainda não foi configurada.');var c=loaded.config;
  if(!validateDate_(dateText,c.timezone,true).ok)return invalidRequest_();var calendars=getCalendars_(c);if(!calendars.ok)return response_(false,'CONFIGURATION_REQUIRED','As agendas configuradas não estão disponíveis.');
  if(startTime||endTime){if(!isValidExactInterval_(startTime,endTime,c))return invalidRequest_();var available=exactIntervalIsAvailable_(dateText,startTime,endTime,c,calendars);return response_(true,'AVAILABILITY_OK','Disponibilidade consultada.',null,{date:dateText,startTime:startTime,endTime:endTime,available:available,unavailable:!available});}
  var slots=calculateAvailableSlots_(dateText,c,calendars.availability);
  return response_(true,'AVAILABILITY_OK','Disponibilidade consultada.',null,{date:dateText,available:slots,unavailable:[]});
}
// Exclusividade de horário deixou de ser decidida no envio da pré-solicitação: um atendimento já
// confirmado não torna mais um horário "ocupado" aqui (a Pati decide caso a caso, na confirmação
// — inclusive aceitando sobreposição deliberada, ex.: passeio em grupo). Só um bloqueio de
// disponibilidade (AVAILABILITY_CALENDAR_ID) continua sendo parada absoluta neste cálculo público.
function calculateAvailableSlots_(dateText,c,availabilityCalendar){
  var day=createDayRange_(dateText,c.timezone),busy=availabilityCalendar.getEvents(day.start,day.end),slots=[];
  for(var minute=c.workdayStartMinutes;minute+c.slotIntervalMinutes<=c.workdayEndMinutes;minute+=c.slotIntervalMinutes){var time=minutesToTime_(minute),end=minutesToTime_(minute+c.slotIntervalMinutes),interval=createExactInterval_(dateText,time,end,c);if(!intervalHasStarted_(interval)&&!eventsOverlap_(busy,interval))slots.push(time);}return slots;
}
function isValidExactInterval_(startTime,endTime,c){var start=timeToMinutes_(startTime),end=timeToMinutes_(endTime);return start>=c.workdayStartMinutes&&start<c.workdayEndMinutes&&end>start&&end<=c.workdayEndMinutes;}
function exactIntervalIsAvailable_(date,startTime,endTime,c,calendars){if(!isValidExactInterval_(startTime,endTime,c))return false;var interval=createExactInterval_(date,startTime,endTime,c);if(intervalHasStarted_(interval))return false;return !eventsOverlap_(calendars.availability.getEvents(interval.start,interval.end),interval);}
function slotIsAvailable_(date,time,c,calendars){var minute=timeToMinutes_(time);return isValidSlotTime_(time,c)&&exactIntervalIsAvailable_(date,time,minutesToTime_(minute+c.slotIntervalMinutes),c,calendars);}
function eventsOverlap_(events,interval){return events.some(function(event){return !isCancelledEvent_(event)&&event.getStartTime().getTime()<interval.end.getTime()&&event.getEndTime().getTime()>interval.start.getTime();});}
function isCancelledEvent_(event){return typeof event.getEventStatus==='function'&&String(event.getEventStatus()).toLowerCase()==='canceled';}

function requestResponse_(payload,suppliedConfig){
  var loaded=suppliedConfig?{ok:true,config:suppliedConfig}:loadConfig_();if(!loaded.ok)return configurationRequired_();var c=loaded.config,requestId=validRequestId_(payload&&payload.requestId)?String(payload.requestId).trim():'';
  if(payload&&payload.requestId&&!requestId)return invalidRequest_();
  var calendars=getCalendars_(c),sheets=getValidatedRequestSheet_(c),modernPayload=payload&&typeof payload.startTime==='string'&&Boolean(payload.startTime.trim())&&typeof payload.endTime==='string'&&Boolean(payload.endTime.trim());if(!calendars.ok||!sheets.ok||modernPayload&&!sheets.requests.hasEndTime)return configurationRequired_(requestId);
  var preexisting=findRequestRows_(sheets.requests,requestId);if(preexisting.length>1)return response_(false,'INCONSISTENT_STATE','Não foi possível registrar a pré-solicitação.',requestId);var preexistingRow=preexisting.length===1?preexisting[0]:null;
  var validated=null,clean=null;if(!preexistingRow){validated=validateRequest_(payload,c);if(!validated.ok)return invalidRequest_();clean=validated.value;requestId=clean.requestId||Utilities.getUuid();if(!(clean.legacy?slotIsAvailable_(clean.date,clean.time,c,calendars):exactIntervalIsAvailable_(clean.date,clean.startTime,clean.endTime,c,calendars)))return response_(false,clean.legacy?'SLOT_UNAVAILABLE':'INTERVAL_UNAVAILABLE','O período solicitado não está disponível.',requestId);}
  var lock=LockService.getScriptLock();if(!lock.tryLock(LOCK_TIMEOUT_MS))return response_(false,'LOCK_TIMEOUT','A agenda está ocupada. Tente novamente em instantes.',requestId);
  try{
    var matches=findRequestRows_(sheets.requests,requestId);if(matches.length>1)return response_(false,'INCONSISTENT_STATE','Não foi possível registrar a pré-solicitação.',requestId);var row=matches.length===1?matches[0]:null;
    if(row){var previous=String(row.values[13]||'');if(previous==='SENT')return response_(true,'REQUEST_CREATED','Esta pré-solicitação já havia sido registrada como pendente.',requestId,null,'SENT');var stored=requestDataFromRow_(row);var retry=notifyByEmail_(row,stored,requestId,c);return response_(true,'REQUEST_CREATED','Esta pré-solicitação já havia sido registrada como pendente.',requestId,null,retry);}
    if(!consumeRateLimit_(clean.whatsapp||clean.email.toLowerCase(),c))return response_(false,'RATE_LIMITED','Muitas solicitações foram recebidas. Aguarde antes de tentar novamente.',requestId);
    if(!(clean.legacy?slotIsAvailable_(clean.date,clean.time,c,calendars):exactIntervalIsAvailable_(clean.date,clean.startTime,clean.endTime,c,calendars)))return response_(false,clean.legacy?'SLOT_UNAVAILABLE':'INTERVAL_UNAVAILABLE','O período solicitado não está mais disponível.',requestId);
    var createdAt=formatTimestamp_(now_(),c),initialStatus=clean.submissionChannel==='email'?'PENDING':'NOT_REQUESTED';
    var requestRow=[requestId,createdAt,clean.submissionChannel,sheetText_(clean.serviceId),clean.date,clean.time,sheetText_(clean.responsibleName),sheetText_(clean.whatsapp),sheetText_(clean.email),sheetText_(clean.petName),sheetText_(clean.region),sheetText_(clean.notes),'PENDENTE',initialStatus,createdAt];if(sheets.requests.hasEndTime)requestRow.push(clean.endTime);while(requestRow.length<sheets.requests.columns)requestRow.push('');if(sheets.requests.hasAddress)requestRow[19]=sheetText_(clean.address);
    try{sheets.requests.sheet.appendRow(requestRow);}catch(error){logTechnical_('SHEET_WRITE_FAILED',requestId);return response_(false,'PERSISTENCE_FAILED','Não foi possível registrar a solicitação.',requestId);}
    var stored=findRequestRow_(sheets.requests,requestId),notification=notifyByEmail_(stored,clean,requestId,c);return response_(true,'REQUEST_CREATED','Pré-solicitação criada como PENDENTE para análise manual.',requestId,null,notification);
  }finally{lock.releaseLock();}
}
function loadConfig_(){var p=PropertiesService.getScriptProperties().getProperties();for(var i=0;i<REQUIRED_PROPERTIES.length;i++)if(!hasProperty_(p,REQUIRED_PROPERTIES[i]))return {ok:false};try{var interval=Number(p.SLOT_INTERVAL_MINUTES),start=timeToMinutes_(p.WORKDAY_START_TIME),end=timeToMinutes_(p.WORKDAY_END_TIME),services=JSON.parse(p.ALLOWED_SERVICE_IDS_JSON),maxBytes=Number(p.MAX_REQUEST_BYTES),window=Number(p.RATE_LIMIT_WINDOW_MINUTES),maximum=Number(p.RATE_LIMIT_MAX_REQUESTS);if(start<0||end<0||start>=end||!integerIn_(interval,1,1440)||(end-start)%interval!==0||!integerIn_(maxBytes,256,1000000)||!integerIn_(window,1,360)||!integerIn_(maximum,1,1000))return {ok:false};if(!Array.isArray(services)||!services.length||services.some(function(x){return typeof x!=='string'||!x.trim()||x.length>80||hasControlCharacters_(x);}))return {ok:false};if(p.PRIVACY_POLICY_VERSION.length>80||hasControlCharacters_(p.PRIVACY_POLICY_VERSION)||p.RATE_LIMIT_SALT.length<8||!normalizeWhatsapp_(p.WHATSAPP_NUMBER)||!/^(true|false)$/i.test(p.EMAIL_NOTIFICATIONS_ENABLED))return {ok:false};Utilities.formatDate(new Date(),p.TIMEZONE,'yyyy-MM-dd');return {ok:true,config:{availabilityCalendarId:p.AVAILABILITY_CALENDAR_ID,appointmentsCalendarId:p.APPOINTMENTS_CALENDAR_ID,spreadsheetId:p.SPREADSHEET_ID,timezone:p.TIMEZONE,workdayStartTime:p.WORKDAY_START_TIME,workdayEndTime:p.WORKDAY_END_TIME,workdayStartMinutes:start,workdayEndMinutes:end,slotIntervalMinutes:interval,allowedServiceIds:services,privacyPolicyVersion:p.PRIVACY_POLICY_VERSION,maxRequestBytes:maxBytes,rateLimitWindowMinutes:window,rateLimitMaxRequests:maximum,rateLimitSalt:p.RATE_LIMIT_SALT,notificationEmail:p.NOTIFICATION_EMAIL.trim(),emailNotificationsEnabled:p.EMAIL_NOTIFICATIONS_ENABLED.toLowerCase()==='true'}};}catch(error){return {ok:false};}}
function loadSpreadsheetConfig_(properties){var p=properties||PropertiesService.getScriptProperties().getProperties();return hasProperty_(p,'SPREADSHEET_ID')?{ok:true,config:{spreadsheetId:p.SPREADSHEET_ID.trim()}}:{ok:false};}
function hasProperty_(p,key){return typeof p[key]==='string'&&Boolean(p[key].trim());}function integerIn_(x,min,max){return Number.isInteger(x)&&x>=min&&x<=max;}function timeToMinutes_(x){if(typeof x!=='string'||!isValidTime_(x))return -1;var parts=x.split(':');return Number(parts[0])*60+Number(parts[1]);}function minutesToTime_(x){return ('0'+Math.floor(x/60)).slice(-2)+':'+('0'+x%60).slice(-2);}function isValidSlotTime_(x,c){var minute=timeToMinutes_(x);return minute>=c.workdayStartMinutes&&minute<c.workdayEndMinutes&&(minute-c.workdayStartMinutes)%c.slotIntervalMinutes===0&&minute+c.slotIntervalMinutes<=c.workdayEndMinutes;}
function getCalendars_(c){try{var availability=CalendarApp.getCalendarById(c.availabilityCalendarId),appointments=CalendarApp.getCalendarById(c.appointmentsCalendarId);return availability&&appointments?{ok:true,availability:availability,appointments:appointments}:{ok:false};}catch(error){return {ok:false};}}
function openSpreadsheet_(c){return SpreadsheetApp.openById(c.spreadsheetId);}
function getValidatedRequestSheet_(c){try{var requests=validateRequestSheet_(openSpreadsheet_(c).getSheetByName('Solicitações'));return requests?{ok:true,requests:requests}:{ok:false};}catch(error){logTechnical_('SHEET_STRUCTURE_INVALID');return {ok:false};}}
function validateSheet_(sheet,expected){if(!sheet||sheet.getLastColumn()!==expected.length)return null;var actual=sheet.getRange(1,1,1,expected.length).getValues()[0];for(var i=0;i<expected.length;i++)if(actual[i]!==expected[i])return null;return sheet;}
function validateRequestSheet_(sheet){if(!sheet)return null;var columns=sheet.getLastColumn(),expected=SHEET_HEADERS.requests;if(columns<expected.length||columns>expected.length+5)return null;var actual=sheet.getRange(1,1,1,columns).getValues()[0];for(var i=0;i<expected.length;i++)if(actual[i]!==expected[i])return null;if(columns>=16&&actual[15]!==SHEET_HEADERS.requestEnd)return null;if(columns>=17&&actual[16]!==SHEET_HEADERS.requestEvent)return null;if(columns>=18&&actual[17]!==SHEET_HEADERS.requestAdminNote)return null;if(columns>=19&&actual[18]!==SHEET_HEADERS.requestClientId)return null;if(columns>=20&&actual[19]!==SHEET_HEADERS.requestAddress)return null;return {sheet:sheet,hasEndTime:columns>=16,hasAddress:columns>=20,columns:columns};}
function getPaymentRows_(sheet){return sheet.getLastRow()<2?[]:sheet.getRange(2,1,sheet.getLastRow()-1,SHEET_HEADERS.payments.length).getValues();}
function appendPaymentRow_(sheet,values){if(!Array.isArray(values)||values.length!==SHEET_HEADERS.payments.length)throw new Error('invalid payment row');sheet.appendRow(values);}
function findRequestRows_(requestSheet,id){var sheet=requestSheet&&requestSheet.sheet,matches=[];if(!sheet||!id||sheet.getLastRow()<2)return matches;var rows=sheet.getRange(2,1,sheet.getLastRow()-1,requestSheet.columns).getValues();for(var i=0;i<rows.length;i++)if(String(rows[i][0])===id)matches.push({row:i+2,values:rows[i],sheet:sheet});return matches;}
function findRequestRow_(requestSheet,id){var matches=findRequestRows_(requestSheet,id);return matches.length===1?matches[0]:null;}
function requestDataFromRow_(row){var x=row.values;return {requestId:String(x[0]||''),submissionChannel:String(x[2]||''),serviceId:String(x[3]||''),date:String(x[4]||''),time:String(x[5]||''),responsibleName:String(x[6]||''),whatsapp:String(x[7]||''),email:String(x[8]||''),petName:String(x[9]||''),region:String(x[10]||''),notes:String(x[11]||''),startTime:String(x[5]||''),endTime:String(x[15]||''),address:String(x[19]||'')};}
function sheetText_(value){var text=String(value===null||value===undefined?'':value);return /^[=+\-@]/.test(text)?"'"+text:text;}
function upsertClient_(sheet,clean,c){var rows=sheet.getLastRow()<2?[]:sheet.getRange(2,1,sheet.getLastRow()-1,SHEET_HEADERS.clients.length).getValues(),phone=clean.whatsapp,emailKey=clean.email.toLowerCase(),found=-1;for(var i=0;i<rows.length;i++){if(phone&&normalizeWhatsapp_(String(rows[i][2]||''))===phone){found=i;break;}if(!phone&&emailKey&&String(rows[i][3]||'').trim().toLowerCase()===emailKey){found=i;break;}}if(found<0){sheet.appendRow([Utilities.getUuid(),sheetText_(clean.responsibleName),sheetText_(phone),sheetText_(clean.email),sheetText_(clean.petName),'',formatTimestamp_(now_(),c),'']);return;}var row=rows[found],pets=String(row[4]||'').split(',').map(function(x){return x.trim();}).filter(Boolean);if(!pets.some(function(x){return x.toLowerCase()===clean.petName.toLowerCase();}))pets.push(clean.petName);row[1]=sheetText_(clean.responsibleName);row[2]=phone?sheetText_(phone):row[2];row[3]=clean.email?sheetText_(clean.email):row[3];row[4]=sheetText_(pets.join(', '));sheet.getRange(found+2,1,1,SHEET_HEADERS.clients.length).setValues([row]);}
function updateNotificationStatus_(row,status,c){if(row){row.sheet.getRange(row.row,14).setValue(status);row.sheet.getRange(row.row,15).setValue(formatTimestamp_(now_(),c));row.values[13]=status;}}
function notifyByEmail_(row,clean,requestId,c){if(clean.submissionChannel!=='email')return 'NOT_REQUESTED';var previous=row?String(row.values[13]||''):'PENDING';if(previous==='SENT')return 'SENT';if(!c.emailNotificationsEnabled||!normalizeEmail_(c.notificationEmail))return previous==='FAILED'?'FAILED':'PENDING';updateNotificationStatus_(row,'PENDING',c);try{MailApp.sendEmail({to:c.notificationEmail,subject:'Nova pré-solicitação PENDENTE — '+singleLine_(clean.petName),body:buildEmailBody_(clean,requestId),replyTo:clean.email});updateNotificationStatus_(row,'SENT',c);return 'SENT';}catch(error){updateNotificationStatus_(row,'FAILED',c);logTechnical_('EMAIL_NOTIFICATION_FAILED',requestId);return 'FAILED';}}
function buildEmailBody_(x,id){var lines=['requestId: '+id,'Status: PENDENTE','Canal escolhido: e-mail','Responsável: '+singleLine_(x.responsibleName)];if(x.whatsapp)lines.push('WhatsApp: '+x.whatsapp);lines.push('E-mail: '+x.email,'Pet: '+singleLine_(x.petName),'Serviço: '+singleLine_(x.serviceId),'Data: '+x.date,'Início: '+(x.startTime||x.time),'Término: '+(x.endTime||'não informado'),'Região: '+singleLine_(x.region));if(x.address)lines.push('Endereço: '+singleLine_(x.address));if(x.notes)lines.push('Observações: '+x.notes);return lines.join('\n');}
function validateRequest_(payload,c){if(!payload||Object.keys(payload).some(function(k){return ALLOWED_POST_FIELDS.indexOf(k)<0;})||String(payload.honeypot||'').trim())return {ok:false};var hasTime=typeof payload.time==='string'&&Boolean(payload.time.trim()),hasStart=typeof payload.startTime==='string'&&Boolean(payload.startTime.trim()),hasEnd=typeof payload.endTime==='string'&&Boolean(payload.endTime.trim()),legacy=hasTime&&!hasStart&&!hasEnd,modern=!hasTime&&hasStart&&hasEnd;if(!legacy&&!modern)return {ok:false};var required=['serviceId','date','responsibleName','petName','region','address','privacyPolicyVersion','submissionChannel'];if(legacy)required.push('time');else required.push('startTime','endTime');for(var i=0;i<required.length;i++)if(typeof payload[required[i]]!=='string'||!payload[required[i]].trim())return {ok:false};if(payload.reviewAccepted!==true&&payload.reviewAccepted!=='true'||payload.privacyAccepted!==true&&payload.privacyAccepted!=='true'||payload.privacyPolicyVersion!==c.privacyPolicyVersion)return {ok:false};var fields=['serviceId','responsibleName','whatsapp','email','submissionChannel','petName','region','address','notes','privacyPolicyVersion'];for(var j=0;j<fields.length;j++){var value=String(payload[fields[j]]||'').trim();if(value.length>TEXT_LIMITS[fields[j]]||hasControlCharacters_(value))return {ok:false};}if(c.allowedServiceIds.indexOf(payload.serviceId.trim())<0||legacy&&!isValidSlotTime_(payload.time,c)||!legacy&&!isValidExactInterval_(payload.startTime,payload.endTime,c)||!validateDate_(payload.date,c.timezone,true).ok)return {ok:false};var phone=String(payload.whatsapp||'').trim()?normalizeWhatsapp_(payload.whatsapp):'',email=normalizeEmail_(payload.email),channel=String(payload.submissionChannel||'').trim();if(channel!=='whatsapp'&&channel!=='email'||!phone&&!email||channel==='whatsapp'&&!phone||channel==='email'&&!email)return {ok:false};var id=validRequestId_(payload.requestId)?String(payload.requestId).trim():'';if(payload.requestId&&!id)return {ok:false};var start=legacy?payload.time:payload.startTime,end=legacy?minutesToTime_(timeToMinutes_(payload.time)+c.slotIntervalMinutes):payload.endTime;return {ok:true,value:{serviceId:payload.serviceId.trim(),date:payload.date,time:start,startTime:start,endTime:end,legacy:legacy,responsibleName:payload.responsibleName.trim(),whatsapp:phone,email:email,submissionChannel:channel,petName:payload.petName.trim(),region:payload.region.trim(),address:payload.address.trim(),notes:String(payload.notes||'').trim(),requestId:id}};}
function validRequestId_(id){return !id||typeof id==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id.trim());}
function parsePostPayload_(e,maxBytes){if(!e||!e.postData||typeof e.postData.contents!=='string'||!e.postData.contents)return {ok:false};var type=String(e.postData.type||'').toLowerCase();if(!/^application\/x-www-form-urlencoded(?:\s*;\s*charset=[a-z0-9._-]+)?$/.test(type)||Utilities.newBlob(e.postData.contents).getBytes().length>maxBytes)return {ok:false};var p=e.parameter||{};return Object.keys(p).some(function(k){return ALLOWED_POST_FIELDS.indexOf(k)<0;})?{ok:false}:{ok:true,payload:p};}
function rateLimitKey_(identity,c){var bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,c.rateLimitSalt+':'+identity,Utilities.Charset.UTF_8);return 'rate:'+bytes.map(function(b){return ('0'+((b+256)%256).toString(16)).slice(-2);}).join('');}function consumeRateLimit_(identity,c){var cache=CacheService.getScriptCache(),key=rateLimitKey_(identity,c),count=Number(cache.get(key)||'0');if(count>=c.rateLimitMaxRequests)return false;cache.put(key,String(count+1),c.rateLimitWindowMinutes*60);return true;}
function validateDate_(text,tz,range){if(typeof text!=='string'||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(text))return {ok:false};try{var d=Utilities.parseDate(text+' 12:00',tz,'yyyy-MM-dd HH:mm');if(Utilities.formatDate(d,tz,'yyyy-MM-dd')!==text)return {ok:false};if(range){var today=Utilities.parseDate(Utilities.formatDate(now_(),tz,'yyyy-MM-dd')+' 12:00',tz,'yyyy-MM-dd HH:mm'),days=Math.round((d-today)/86400000);if(days<0||days>MAX_FUTURE_DAYS)return {ok:false};}return {ok:true,date:d};}catch(error){return {ok:false};}}
function createExactInterval_(date,startTime,endTime,c){return {start:Utilities.parseDate(date+' '+startTime,c.timezone,'yyyy-MM-dd HH:mm'),end:Utilities.parseDate(date+' '+endTime,c.timezone,'yyyy-MM-dd HH:mm')};}
function createDayRange_(date,tz){var start=Utilities.parseDate(date+' 00:00',tz,'yyyy-MM-dd HH:mm');return {start:start,end:new Date(start.getTime()+86400000)};}function createInterval_(date,time,c){var start=Utilities.parseDate(date+' '+time,c.timezone,'yyyy-MM-dd HH:mm');return {start:start,end:new Date(start.getTime()+c.slotIntervalMinutes*60000)};}function formatTimestamp_(date,c){return Utilities.formatDate(date,c.timezone,"yyyy-MM-dd'T'HH:mm:ss");}function now_(){return new Date();}function intervalHasStarted_(x){return x.start.getTime()<=now_().getTime();}
function normalizeEmail_(x){if(typeof x!=='string'||x.length>254||hasControlCharacters_(x))return '';var v=x.trim();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)?v:'';}function isValidTime_(x){return typeof x==='string'&&/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(x);}function normalizeWhatsapp_(x){if(typeof x!=='string'||hasControlCharacters_(x))return '';var d=x.replace(/\D/g,'');return /^\d{10,15}$/.test(d)?d:'';}function hasControlCharacters_(x){return /[\u0000-\u001F\u007F]/.test(x);}function singleLine_(x){return String(x).replace(/[\r\n]+/g,' ').trim();}
function getParameter_(e,n){return e&&e.parameter&&typeof e.parameter[n]==='string'?e.parameter[n]:'';}function response_(ok,code,message,id,data,notificationStatus){var x={ok:ok,code:code,message:message};if(id)x.requestId=id;if(data!==undefined&&data!==null)x.data=data;if(notificationStatus)x.notificationStatus=notificationStatus;return x;}function jsonResponse_(p){return ContentService.createTextOutput(JSON.stringify(p)).setMimeType(ContentService.MimeType.JSON);}function logTechnical_(code,id){console.error(code+(id?' requestId='+id:''));}
