/** Backend público de pré-solicitações. Configuração operacional: Script Properties. */
var SERVICE_NAME = 'pati-mundopet-scheduling';
var SERVICE_VERSION = '2.0.0';
var MAX_FUTURE_DAYS = 90;
var LOCK_TIMEOUT_MS = 5000;
var REQUIRED_PROPERTIES = ['AVAILABILITY_CALENDAR_ID','APPOINTMENTS_CALENDAR_ID','SPREADSHEET_ID','TIMEZONE','SLOT_DURATION_MINUTES','AVAILABILITY_EVENT_PREFIX','ALLOWED_SERVICE_IDS_JSON','PENDING_EVENT_PREFIX','WHATSAPP_NUMBER','PRIVACY_POLICY_VERSION','MAX_REQUEST_BYTES','RATE_LIMIT_WINDOW_MINUTES','RATE_LIMIT_MAX_REQUESTS','RATE_LIMIT_SALT','PENDING_RETENTION_DAYS','NOTIFICATION_EMAIL','EMAIL_NOTIFICATIONS_ENABLED'];
var ALLOWED_POST_FIELDS = ['action','serviceId','date','time','responsibleName','whatsapp','petName','region','notes','reviewAccepted','privacyAccepted','privacyPolicyVersion','honeypot','requestId','email','submissionChannel'];
var TEXT_LIMITS = {serviceId:80,responsibleName:120,whatsapp:20,email:254,submissionChannel:10,petName:80,region:120,notes:1000,privacyPolicyVersion:80,requestId:36};
var SHEET_HEADERS = {
  requests:['requestId','dataRecebimento','submissionChannel','serviço','data','horário','responsável','WhatsApp','e-mail','pet','região','observações','status','notificationStatus','dataÚltimaAtualização'],
  clients:['clienteId','responsável','WhatsApp','e-mail','pets','observações','dataCadastro','últimoAtendimento'],
  payments:['requestId','cliente','serviço','valor','formaPagamento','vencimento','statusPagamento','dataPagamento','observações']
};

function doGet(e){try{var action=getParameter_(e,'action');if(action==='health')return jsonResponse_(healthResponse_());if(action==='availability')return jsonResponse_(availabilityResponse_(getParameter_(e,'date')));return jsonResponse_(invalidRequest_());}catch(error){logTechnical_('GET_INTERNAL');return jsonResponse_(response_(false,'INTERNAL_ERROR','Não foi possível processar a solicitação.'));}}
function doPost(e){var requestId='';try{var loaded=loadConfig_();if(!loaded.ok)return jsonResponse_(response_(false,'CONFIGURATION_REQUIRED','A integração ainda não foi configurada.'));var parsed=parsePostPayload_(e,loaded.config.maxRequestBytes);if(!parsed.ok||parsed.payload.action!=='request')return jsonResponse_(invalidRequest_());requestId=String(parsed.payload.requestId||'');return jsonResponse_(requestResponse_(parsed.payload,loaded.config));}catch(error){logTechnical_('POST_INTERNAL',requestId);return jsonResponse_(response_(false,'INTERNAL_ERROR','Não foi possível processar a solicitação.',requestId));}}
function invalidRequest_(){return response_(false,'INVALID_REQUEST','Solicitação inválida.');}
function healthResponse_(){var p=PropertiesService.getScriptProperties().getProperties(),loaded=loadConfig_();return {ok:true,code:'HEALTH_OK',message:'Serviço de diagnóstico disponível.',service:SERVICE_NAME,version:SERVICE_VERSION,configured:loaded.ok,spreadsheetConfigured:hasProperty_(p,'SPREADSHEET_ID'),availabilityCalendarConfigured:hasProperty_(p,'AVAILABILITY_CALENDAR_ID'),appointmentsCalendarConfigured:hasProperty_(p,'APPOINTMENTS_CALENDAR_ID'),timestamp:new Date().toISOString()};}

function availabilityResponse_(dateText){
  var loaded=loadConfig_();if(!loaded.ok)return response_(false,'CONFIGURATION_REQUIRED','A integração ainda não foi configurada.');var c=loaded.config;
  if(!validateDate_(dateText,c.timezone,true).ok)return invalidRequest_();var calendars=getCalendars_(c);if(!calendars.ok)return response_(false,'CONFIGURATION_REQUIRED','As agendas configuradas não estão disponíveis.');
  var slots=calculateAvailableSlots_(dateText,c,calendars.availability,calendars.appointments);
  // Compatibilidade com o cliente atual: horários ocupados nunca são publicados.
  return response_(true,'AVAILABILITY_OK','Disponibilidade consultada.',null,{date:dateText,available:slots,unavailable:[]});
}
function calculateAvailableSlots_(dateText,c,availabilityCalendar,appointmentsCalendar){
  var day=createDayRange_(dateText,c.timezone),busy=appointmentsCalendar.getEvents(day.start,day.end),unique={};
  availabilityCalendar.getEvents(day.start,day.end).forEach(function(event){
    if(isCancelledEvent_(event)||String(event.getTitle()).indexOf(c.availabilityPrefix)!==0)return;
    var cursor=new Date(Math.max(event.getStartTime().getTime(),day.start.getTime())),blockEnd=new Date(Math.min(event.getEndTime().getTime(),day.end.getTime()));
    while(cursor.getTime()+c.slotDurationMinutes*60000<=blockEnd.getTime()){
      var interval={start:new Date(cursor),end:new Date(cursor.getTime()+c.slotDurationMinutes*60000)};
      if(!intervalHasStarted_(interval)&&!eventsOverlap_(busy,interval))unique[Utilities.formatDate(interval.start,c.timezone,'HH:mm')]=true;
      cursor=new Date(cursor.getTime()+c.slotDurationMinutes*60000);
    }
  });
  return Object.keys(unique).sort();
}
function slotIsAvailable_(date,time,c,calendars){var interval=createInterval_(date,time,c);if(intervalHasStarted_(interval))return false;var offered=calendars.availability.getEvents(interval.start,interval.end).some(function(event){return !isCancelledEvent_(event)&&String(event.getTitle()).indexOf(c.availabilityPrefix)===0&&event.getStartTime().getTime()<=interval.start.getTime()&&event.getEndTime().getTime()>=interval.end.getTime();});return offered&&!eventsOverlap_(calendars.appointments.getEvents(interval.start,interval.end),interval);}
function eventsOverlap_(events,interval){return events.some(function(event){return !isCancelledEvent_(event)&&event.getStartTime().getTime()<interval.end.getTime()&&event.getEndTime().getTime()>interval.start.getTime();});}
function isCancelledEvent_(event){return typeof event.getEventStatus==='function'&&String(event.getEventStatus()).toLowerCase()==='canceled';}

function requestResponse_(payload,suppliedConfig){
  var loaded=suppliedConfig?{ok:true,config:suppliedConfig}:loadConfig_();if(!loaded.ok)return response_(false,'CONFIGURATION_REQUIRED','A integração ainda não foi configurada.');var c=loaded.config,validated=validateRequest_(payload,c);if(!validated.ok)return invalidRequest_();var clean=validated.value,requestId=clean.requestId||Utilities.getUuid();
  var calendars=getCalendars_(c),sheets=getValidatedSheets_(c);if(!calendars.ok||!sheets.ok)return response_(false,'CONFIGURATION_REQUIRED','A estrutura administrativa ainda não foi configurada.',requestId);
  var preexistingEvent=findRequestEvent_(calendars.appointments,requestId,c),preexistingRow=findRequestRow_(sheets.requests,requestId);
  if(!preexistingEvent&&!preexistingRow&&!slotIsAvailable_(clean.date,clean.time,c,calendars))return response_(false,'SLOT_UNAVAILABLE','O horário selecionado não está disponível.',requestId);
  var lock=LockService.getScriptLock();if(!lock.tryLock(LOCK_TIMEOUT_MS))return response_(false,'LOCK_TIMEOUT','A agenda está ocupada. Tente novamente em instantes.',requestId);
  try{
    var event=findRequestEvent_(calendars.appointments,requestId,c),row=findRequestRow_(sheets.requests,requestId);if(Boolean(event)!==Boolean(row)){logTechnical_('INCONSISTENT_STATE',requestId);return response_(false,'INCONSISTENT_STATE','A solicitação requer reconciliação administrativa.',requestId);}
    if(event&&row){var previous=String(row.values[13]||'');if(previous==='SENT')return response_(true,'REQUEST_CREATED','Esta pré-solicitação já havia sido registrada como pendente.',requestId,null,'SENT');var retry=notifyByEmail_(event,row,clean,requestId,c);return response_(true,'REQUEST_CREATED','Esta pré-solicitação já havia sido registrada como pendente.',requestId,null,retry);}
    if(!consumeRateLimit_(clean.whatsapp||clean.email.toLowerCase(),c))return response_(false,'RATE_LIMITED','Muitas solicitações foram recebidas. Aguarde antes de tentar novamente.',requestId);
    if(!slotIsAvailable_(clean.date,clean.time,c,calendars))return response_(false,'SLOT_UNAVAILABLE','O horário selecionado não está mais disponível.',requestId);
    var createdAt=formatTimestamp_(now_(),c),initialStatus=clean.submissionChannel==='email'?'PENDING':'NOT_REQUESTED',interval=createInterval_(clean.date,clean.time,c);
    var eventCreated=calendars.appointments.createEvent(c.pendingPrefix+' '+singleLine_(clean.petName)+' — '+singleLine_(clean.serviceId),interval.start,interval.end,{description:buildEventDescription_(clean,requestId,createdAt,initialStatus)});
    var requestRow=[requestId,createdAt,clean.submissionChannel,clean.serviceId,clean.date,clean.time,clean.responsibleName,clean.whatsapp,clean.email,clean.petName,clean.region,clean.notes,'PENDENTE',initialStatus,createdAt];
    try{sheets.requests.appendRow(requestRow);upsertClient_(sheets.clients,clean,c);}catch(error){try{eventCreated.deleteEvent();}catch(compensationError){logTechnical_('COMPENSATION_FAILED',requestId);}logTechnical_('SHEET_WRITE_FAILED',requestId);return response_(false,'PERSISTENCE_FAILED','Não foi possível registrar a solicitação.',requestId);}
    var stored=findRequestRow_(sheets.requests,requestId),notification=notifyByEmail_(eventCreated,stored,clean,requestId,c);return response_(true,'REQUEST_CREATED','Pré-solicitação criada como PENDENTE para análise manual.',requestId,null,notification);
  }finally{lock.releaseLock();}
}
function loadConfig_(){var p=PropertiesService.getScriptProperties().getProperties();for(var i=0;i<REQUIRED_PROPERTIES.length;i++)if(!hasProperty_(p,REQUIRED_PROPERTIES[i]))return {ok:false};try{var duration=Number(p.SLOT_DURATION_MINUTES),services=JSON.parse(p.ALLOWED_SERVICE_IDS_JSON),maxBytes=Number(p.MAX_REQUEST_BYTES),window=Number(p.RATE_LIMIT_WINDOW_MINUTES),maximum=Number(p.RATE_LIMIT_MAX_REQUESTS),retention=Number(p.PENDING_RETENTION_DAYS);if(!integerIn_(duration,1,1440)||!integerIn_(maxBytes,256,1000000)||!integerIn_(window,1,360)||!integerIn_(maximum,1,1000)||!integerIn_(retention,1,3650))return {ok:false};if(!Array.isArray(services)||!services.length||services.some(function(x){return typeof x!=='string'||!x.trim()||x.length>80||hasControlCharacters_(x);}))return {ok:false};if(!validPrefix_(p.AVAILABILITY_EVENT_PREFIX)||!validPrefix_(p.PENDING_EVENT_PREFIX)||p.PRIVACY_POLICY_VERSION.length>80||hasControlCharacters_(p.PRIVACY_POLICY_VERSION)||p.RATE_LIMIT_SALT.length<8||!normalizeWhatsapp_(p.WHATSAPP_NUMBER)||!/^(true|false)$/i.test(p.EMAIL_NOTIFICATIONS_ENABLED))return {ok:false};Utilities.formatDate(new Date(),p.TIMEZONE,'yyyy-MM-dd');return {ok:true,config:{availabilityCalendarId:p.AVAILABILITY_CALENDAR_ID,appointmentsCalendarId:p.APPOINTMENTS_CALENDAR_ID,spreadsheetId:p.SPREADSHEET_ID,timezone:p.TIMEZONE,slotDurationMinutes:duration,availabilityPrefix:p.AVAILABILITY_EVENT_PREFIX,allowedServiceIds:services,pendingPrefix:p.PENDING_EVENT_PREFIX,privacyPolicyVersion:p.PRIVACY_POLICY_VERSION,maxRequestBytes:maxBytes,rateLimitWindowMinutes:window,rateLimitMaxRequests:maximum,rateLimitSalt:p.RATE_LIMIT_SALT,pendingRetentionDays:retention,notificationEmail:p.NOTIFICATION_EMAIL.trim(),emailNotificationsEnabled:p.EMAIL_NOTIFICATIONS_ENABLED.toLowerCase()==='true'}};}catch(error){return {ok:false};}}
function hasProperty_(p,key){return typeof p[key]==='string'&&Boolean(p[key].trim());}function integerIn_(x,min,max){return Number.isInteger(x)&&x>=min&&x<=max;}function validPrefix_(x){return x.length<=40&&!hasControlCharacters_(x);}
function getCalendars_(c){var availability=CalendarApp.getCalendarById(c.availabilityCalendarId),appointments=CalendarApp.getCalendarById(c.appointmentsCalendarId);return availability&&appointments?{ok:true,availability:availability,appointments:appointments}:{ok:false};}
function openSpreadsheet_(c){return SpreadsheetApp.openById(c.spreadsheetId);}
function getValidatedSheets_(c){try{var spreadsheet=openSpreadsheet_(c),requests=validateSheet_(spreadsheet.getSheetByName('Solicitações'),SHEET_HEADERS.requests),clients=validateSheet_(spreadsheet.getSheetByName('Clientes'),SHEET_HEADERS.clients),payments=validateSheet_(spreadsheet.getSheetByName('Pagamentos'),SHEET_HEADERS.payments);return requests&&clients&&payments?{ok:true,requests:requests,clients:clients,payments:payments}:{ok:false};}catch(error){logTechnical_('SHEET_STRUCTURE_INVALID');return {ok:false};}}
function validateSheet_(sheet,expected){if(!sheet||sheet.getLastColumn()!==expected.length)return null;var actual=sheet.getRange(1,1,1,expected.length).getValues()[0];for(var i=0;i<expected.length;i++)if(actual[i]!==expected[i])return null;return sheet;}
function getPaymentRows_(sheet){return sheet.getLastRow()<2?[]:sheet.getRange(2,1,sheet.getLastRow()-1,SHEET_HEADERS.payments.length).getValues();}
function appendPaymentRow_(sheet,values){if(!Array.isArray(values)||values.length!==SHEET_HEADERS.payments.length)throw new Error('invalid payment row');sheet.appendRow(values);}
function findRequestRow_(sheet,id){if(!id||sheet.getLastRow()<2)return null;var rows=sheet.getRange(2,1,sheet.getLastRow()-1,SHEET_HEADERS.requests.length).getValues();for(var i=0;i<rows.length;i++)if(String(rows[i][0])===id)return {row:i+2,values:rows[i],sheet:sheet};return null;}
function upsertClient_(sheet,clean,c){var rows=sheet.getLastRow()<2?[]:sheet.getRange(2,1,sheet.getLastRow()-1,SHEET_HEADERS.clients.length).getValues(),phone=clean.whatsapp,emailKey=clean.email.toLowerCase(),found=-1;for(var i=0;i<rows.length;i++){if(phone&&normalizeWhatsapp_(String(rows[i][2]||''))===phone){found=i;break;}if(!phone&&emailKey&&String(rows[i][3]||'').trim().toLowerCase()===emailKey){found=i;break;}}if(found<0){sheet.appendRow([Utilities.getUuid(),clean.responsibleName,phone,clean.email,clean.petName,'',formatTimestamp_(now_(),c),'']);return;}var row=rows[found],pets=String(row[4]||'').split(',').map(function(x){return x.trim();}).filter(Boolean);if(!pets.some(function(x){return x.toLowerCase()===clean.petName.toLowerCase();}))pets.push(clean.petName);row[1]=clean.responsibleName;row[2]=phone||row[2];row[3]=clean.email||row[3];row[4]=pets.join(', ');sheet.getRange(found+2,1,1,SHEET_HEADERS.clients.length).setValues([row]);}
function updateNotificationStatus_(event,row,status,c){setNotificationStatus_(event,status);if(row){row.sheet.getRange(row.row,14).setValue(status);row.sheet.getRange(row.row,15).setValue(formatTimestamp_(now_(),c));row.values[13]=status;}}
function notifyByEmail_(event,row,clean,requestId,c){if(clean.submissionChannel!=='email')return 'NOT_REQUESTED';var previous=row?String(row.values[13]||''):notificationStatus_(event);if(previous==='SENT')return 'SENT';if(!c.emailNotificationsEnabled||!normalizeEmail_(c.notificationEmail))return previous==='FAILED'?'FAILED':'PENDING';updateNotificationStatus_(event,row,'PENDING',c);try{MailApp.sendEmail({to:c.notificationEmail,subject:'Nova pré-solicitação PENDENTE — '+singleLine_(clean.petName),body:buildEmailBody_(clean,requestId),replyTo:clean.email});updateNotificationStatus_(event,row,'SENT',c);return 'SENT';}catch(error){updateNotificationStatus_(event,row,'FAILED',c);logTechnical_('EMAIL_NOTIFICATION_FAILED',requestId);return 'FAILED';}}
function buildEventDescription_(x,id,created,status){var lines=['status: PENDENTE','submissionChannel: '+x.submissionChannel,'notificationStatus: '+status,'responsável: '+singleLine_(x.responsibleName)];if(x.whatsapp)lines.push('WhatsApp: '+x.whatsapp);if(x.email)lines.push('e-mail: '+x.email);lines.push('pet: '+singleLine_(x.petName),'serviço: '+singleLine_(x.serviceId),'região: '+singleLine_(x.region));if(x.notes)lines.push('observações: '+x.notes);lines.push('requestId: '+id,'data de criação: '+created);return lines.join('\n');}
function buildEmailBody_(x,id){var lines=['requestId: '+id,'Status: PENDENTE','Canal escolhido: e-mail','Responsável: '+singleLine_(x.responsibleName)];if(x.whatsapp)lines.push('WhatsApp: '+x.whatsapp);lines.push('E-mail: '+x.email,'Pet: '+singleLine_(x.petName),'Serviço: '+singleLine_(x.serviceId),'Data: '+x.date,'Horário: '+x.time,'Região: '+singleLine_(x.region));if(x.notes)lines.push('Observações: '+x.notes);return lines.join('\n');}
function validateRequest_(payload,c){if(!payload||Object.keys(payload).some(function(k){return ALLOWED_POST_FIELDS.indexOf(k)<0;})||String(payload.honeypot||'').trim())return {ok:false};var required=['serviceId','date','time','responsibleName','petName','region','privacyPolicyVersion','submissionChannel'];for(var i=0;i<required.length;i++)if(typeof payload[required[i]]!=='string'||!payload[required[i]].trim())return {ok:false};if(payload.reviewAccepted!==true&&payload.reviewAccepted!=='true'||payload.privacyAccepted!==true&&payload.privacyAccepted!=='true'||payload.privacyPolicyVersion!==c.privacyPolicyVersion)return {ok:false};var fields=['serviceId','responsibleName','whatsapp','email','submissionChannel','petName','region','notes','privacyPolicyVersion'];for(var j=0;j<fields.length;j++){var value=String(payload[fields[j]]||'').trim();if(value.length>TEXT_LIMITS[fields[j]]||hasControlCharacters_(value))return {ok:false};}if(c.allowedServiceIds.indexOf(payload.serviceId.trim())<0||!isValidTime_(payload.time)||!validateDate_(payload.date,c.timezone,true).ok)return {ok:false};var phone=String(payload.whatsapp||'').trim()?normalizeWhatsapp_(payload.whatsapp):'',email=normalizeEmail_(payload.email),channel=String(payload.submissionChannel||'').trim();if(channel!=='whatsapp'&&channel!=='email'||!phone&&!email||channel==='whatsapp'&&!phone||channel==='email'&&!email)return {ok:false};var id=String(payload.requestId||'').trim();if(id&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id))return {ok:false};return {ok:true,value:{serviceId:payload.serviceId.trim(),date:payload.date,time:payload.time,responsibleName:payload.responsibleName.trim(),whatsapp:phone,email:email,submissionChannel:channel,petName:payload.petName.trim(),region:payload.region.trim(),notes:String(payload.notes||'').trim(),requestId:id}};}
function parsePostPayload_(e,maxBytes){if(!e||!e.postData||typeof e.postData.contents!=='string'||!e.postData.contents)return {ok:false};var type=String(e.postData.type||'').toLowerCase();if(!/^application\/x-www-form-urlencoded(?:\s*;\s*charset=[a-z0-9._-]+)?$/.test(type)||Utilities.newBlob(e.postData.contents).getBytes().length>maxBytes)return {ok:false};var p=e.parameter||{};return Object.keys(p).some(function(k){return ALLOWED_POST_FIELDS.indexOf(k)<0;})?{ok:false}:{ok:true,payload:p};}
function rateLimitKey_(identity,c){var bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,c.rateLimitSalt+':'+identity,Utilities.Charset.UTF_8);return 'rate:'+bytes.map(function(b){return ('0'+((b+256)%256).toString(16)).slice(-2);}).join('');}function consumeRateLimit_(identity,c){var cache=CacheService.getScriptCache(),key=rateLimitKey_(identity,c),count=Number(cache.get(key)||'0');if(count>=c.rateLimitMaxRequests)return false;cache.put(key,String(count+1),c.rateLimitWindowMinutes*60);return true;}
function validateDate_(text,tz,range){if(typeof text!=='string'||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(text))return {ok:false};try{var d=Utilities.parseDate(text+' 12:00',tz,'yyyy-MM-dd HH:mm');if(Utilities.formatDate(d,tz,'yyyy-MM-dd')!==text)return {ok:false};if(range){var today=Utilities.parseDate(Utilities.formatDate(now_(),tz,'yyyy-MM-dd')+' 12:00',tz,'yyyy-MM-dd HH:mm'),days=Math.round((d-today)/86400000);if(days<0||days>MAX_FUTURE_DAYS)return {ok:false};}return {ok:true,date:d};}catch(error){return {ok:false};}}
function createDayRange_(date,tz){var start=Utilities.parseDate(date+' 00:00',tz,'yyyy-MM-dd HH:mm');return {start:start,end:new Date(start.getTime()+86400000)};}function createInterval_(date,time,c){var start=Utilities.parseDate(date+' '+time,c.timezone,'yyyy-MM-dd HH:mm');return {start:start,end:new Date(start.getTime()+c.slotDurationMinutes*60000)};}function formatTimestamp_(date,c){return Utilities.formatDate(date,c.timezone,"yyyy-MM-dd'T'HH:mm:ss");}function now_(){return new Date();}function intervalHasStarted_(x){return x.start.getTime()<=now_().getTime();}
function findRequestEvent_(calendar,id,c){if(!id)return null;var start=new Date(now_().getTime()-(c.pendingRetentionDays+1)*86400000),end=new Date(now_().getTime()+(MAX_FUTURE_DAYS+2)*86400000),events=calendar.getEvents(start,end,{search:id});for(var i=0;i<events.length;i++)if(String(events[i].getDescription()).indexOf('requestId: '+id)>=0)return events[i];return null;}
function notificationStatus_(event){var match=/^notificationStatus: (NOT_REQUESTED|PENDING|SENT|FAILED)$/m.exec(event.getDescription());return match?match[1]:'NOT_REQUESTED';}function setNotificationStatus_(event,status){var description=event.getDescription();description=/^notificationStatus: /m.test(description)?description.replace(/^notificationStatus: .*$/m,'notificationStatus: '+status):description+'\nnotificationStatus: '+status;event.setDescription(description);}
function previewExpiredPendingEvents(){var r=loadConfig_();if(!r.ok)return {ok:false,code:'CONFIGURATION_REQUIRED',total:0,eventIds:[]};var c=r.config,calendar=CalendarApp.getCalendarById(c.appointmentsCalendarId),cutoff=new Date(now_().getTime()-c.pendingRetentionDays*86400000),events=calendar.getEvents(new Date(0),cutoff),ids=events.filter(function(e){return e.getTitle().indexOf(c.pendingPrefix)===0;}).map(function(e){return e.getId();});return {ok:true,code:'RETENTION_PREVIEW',total:ids.length,eventIds:ids};}
function cleanupExpiredPendingEvents(confirmCleanup){var preview=previewExpiredPendingEvents();if(!preview.ok||confirmCleanup!==true)return {ok:preview.ok,code:confirmCleanup===true?preview.code:'CLEANUP_CONFIRMATION_REQUIRED',total:preview.total,removed:0,eventIds:preview.eventIds};var c=loadConfig_().config,calendar=CalendarApp.getCalendarById(c.appointmentsCalendarId),allowed=new Set(preview.eventIds),removed=0;calendar.getEvents(new Date(0),new Date(now_().getTime()-c.pendingRetentionDays*86400000)).forEach(function(e){if(allowed.has(e.getId())&&e.getTitle().indexOf(c.pendingPrefix)===0){e.deleteEvent();removed++;}});return {ok:true,code:'CLEANUP_COMPLETE',total:preview.total,removed:removed,eventIds:preview.eventIds};}
function normalizeEmail_(x){if(typeof x!=='string'||x.length>254||hasControlCharacters_(x))return '';var v=x.trim();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)?v:'';}function isValidTime_(x){return typeof x==='string'&&/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(x);}function normalizeWhatsapp_(x){if(typeof x!=='string'||hasControlCharacters_(x))return '';var d=x.replace(/\D/g,'');return /^\d{10,15}$/.test(d)?d:'';}function hasControlCharacters_(x){return /[\u0000-\u001F\u007F]/.test(x);}function singleLine_(x){return String(x).replace(/[\r\n]+/g,' ').trim();}
function getParameter_(e,n){return e&&e.parameter&&typeof e.parameter[n]==='string'?e.parameter[n]:'';}function response_(ok,code,message,id,data,notificationStatus){var x={ok:ok,code:code,message:message};if(id)x.requestId=id;if(data!==undefined&&data!==null)x.data=data;if(notificationStatus)x.notificationStatus=notificationStatus;return x;}function jsonResponse_(p){return ContentService.createTextOutput(JSON.stringify(p)).setMimeType(ContentService.MimeType.JSON);}function logTechnical_(code,id){console.error(code+(id?' requestId='+id:''));}
